export const NAILDESIGN_LIST_REQUEST = "NAILDESIGN_LIST_REQUEST";
export const NAILDESIGN_LIST_SUCCESS = "NAILDESIGN_LIST_SUCCESS";
export const NAILDESIGN_LIST_FAIL = "NAILDESIGN_LIST_FAIL";

export const NAILDESIGN_DELETE_REQUEST = "NAILDESIGN_DELETE_REQUEST";
export const NAILDESIGN_DELETE_SUCCESS = "NAILDESIGN_DELETE_SUCCESS";
export const NAILDESIGN_DELETE_FAIL = "NAILDESIGN_DELETE_FAIL";
